### ISSUE TITLE
Bloating output code?

### ISSUE THREAD

**Issue by afuggini** [getify/TypL#47]
Very interesting approach!
I am wondering wether it is worth adding to the output JS all those extra functions necessary to validate on runtime? What's the mindset on that?

**Comment by getify** [comment]
> all those extra functions...

The current runtime component is here: https://github.com/getify/TypL/blob/master/lib/runtime.js

Unminified and ungzipped it's only 13.6kb. Minified+gzip is *much* smaller (I forget right now exact size, but like under 5kb I believe). I don't think that size is at all burdensome on hardly any modern frontend JS project.

However, keep in mind, TypL is not necessarily designed to "ship to production", though you could do so if you wanted and didn't mind the 5kb (plus whatever 0.1% increase in your own code's size for runtime type annotations). Since TypL is (or will be!) completely configurable, the idea is that you can put the runtime annotations in the source code and have TypL leave them in for the bundled code you're running in dev/testing/QA, but then have a different TypL config that removed all of that stuff for the production code. That's how I would plan to use it.

You'd likely only leave it in your production code bundles if you were trying to catch type errors in production. So, for example, you might briefly turn on that stuff for your production code while you troubleshoot and remotely log your type errors, then turn it back off.

Also:

* TypL would only include the runtime functions that your code uses (so it would effectively tree-shake in that sense), so in practice it'd be smaller than the maximum 13.6kb file.

* TypL would, depending on config, remove any annotations that are verifiable at compile-time, and only leave the annotations that touch the edges of data sources where runtime typing is required. It's expected that if you code similarly to how you code with TS/Flow, the majority of your typing will be compile-time verifiable, so you should only have a few places where runtime validation was necessary in the first place.

Taking all this into account, I think having the option to do the runtime typing validation is a far greater strength than TS/Flow offer, and far outweighs the maximum/likely *cost*.
